### PR TITLE
Update choose-repository.css

### PR DESCRIPTION
**Pull request by asad1983**
Css changes for rest of the bugs

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Which issue(s) is this supposed to resolve?  I just tested it out but I'm not seeing any change in behavior, though its possible I am looking for the wrong thing.

**Comment by asad1983** [comment]
This change is related to https://github.com/Zoltu/RepoCreator-Client/issues/1.I tested on my end and i cant see star and content wrapping now.

**Comment by MicahZoltu** [comment]
In Chrome simulating a Nexus 5 I still see the overlap: 
image

**Comment by MicahZoltu** [comment]
Closing in favor of #17.

**Pull request closed without merging**
