### PR TITLE
Update choose-repository.css

### PR DESCRIPTION
**Pull request by asad1983**
I have tested for smaller resolution and increase the length of repository names.
https://github.com/Zoltu/RepoCreator-Client/issues/1

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Hmm, I still see the overlap: 
image

Can you show a screenshot of what you see?

**Comment by MicahZoltu** [comment]
Try with this as the popular repository:

``` ts
let popularTemplates = underscore([{provider:"GitHub",owner:"test",name:"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"}]).map((repo: RepositoryWireModel) => new Repository(repo.owner, repo.name, false, false, true, false));
```

Replace https://github.com/Zoltu/RepoCreator-Client/blob/master/dist/source/repo-creator/choose-repository.ts#L227 with the above.  That should make it easier to reproduce the problem I am hoping to have fixed.

**Comment by asad1983** [comment]
Yes with above detail i can see the issue.Actually i increased the length from html page not from .ts file.
I will update you tomorrow.

**Comment by MicahZoltu** [comment]
Closing in favor of #17.

**Pull request closed without merging**
